
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Label;
import java.io.File;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPopupMenu.Separator;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/*

 * To change this license header, choose License Headers in Project Properties.

 * To change this template file, choose Tools | Templates

 * and open the template in the editor.

 */



/**

 *

 * @author ISMAIL

 */

public class EspaceEtd extends javax.swing.JFrame {


protected ArrayList lablist;



    /**

     * Creates new form EspaceEns

     */

    public EspaceEtd() {
        lablist = new ArrayList<JLabel>();
        initComponents();

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Accueil = new javax.swing.JPanel();
        Principale = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        TP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPpane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Cours = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CoursPane = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Exercices = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ExercicesPane = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Affichage = new javax.swing.JPanel();
        Forum = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Etudiant");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 20));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 200, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\circle.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\corner1.png")); // NOI18N
        jLabel10.setEnabled(false);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, 100));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_home_32px.png")); // NOI18N
        jButton5.setText("Accueil");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_collaboration_32px_1.png")); // NOI18N
        jButton4.setText("Forum");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 930, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\corner2.png")); // NOI18N
        jLabel7.setEnabled(false);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 100));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Se déconnecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 240, -1, 35));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_online_support_25px.png")); // NOI18N
        jLabel5.setText("Contact.");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel5);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText(" ");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3);

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_info_50px_2.png")); // NOI18N
        jLabel13.setText("Aide.");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel13);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1280, 80));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\corner4.png")); // NOI18N
        jLabel9.setEnabled(false);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\corner3.png")); // NOI18N
        jLabel8.setEnabled(false);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 100, 110));

        Accueil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Accueil.setName(""); // NOI18N
        Accueil.setLayout(new java.awt.CardLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\etd.png")); // NOI18N
        Principale.add(jLabel30);

        Accueil.add(Principale, "card5");

        TP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TPpane.setLayout(new javax.swing.BoxLayout(TPpane, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(TPpane);

        TP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 930, 330));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Vous étes sur la page des Traveaux Pratiques");
        jPanel1.add(jLabel11);

        TP.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        Accueil.add(TP, "card2");

        Cours.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoursPane.setLayout(new javax.swing.BoxLayout(CoursPane, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(CoursPane);

        Cours.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 930, 330));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Vous étes sur la page des Cours");
        jPanel6.add(jLabel12);

        Cours.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        Accueil.add(Cours, "card2");

        Exercices.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExercicesPane.setLayout(new javax.swing.BoxLayout(ExercicesPane, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(ExercicesPane);

        Exercices.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 930, 330));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Vous étes sur la page des Exercices");
        jPanel7.add(jLabel14);

        Exercices.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        Accueil.add(Exercices, "card2");

        javax.swing.GroupLayout AffichageLayout = new javax.swing.GroupLayout(Affichage);
        Affichage.setLayout(AffichageLayout);
        AffichageLayout.setHorizontalGroup(
            AffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        AffichageLayout.setVerticalGroup(
            AffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        Accueil.add(Affichage, "card6");

        jTextArea1.setBackground(new java.awt.Color(249, 247, 247));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Publier");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ForumLayout = new javax.swing.GroupLayout(Forum);
        Forum.setLayout(ForumLayout);
        ForumLayout.setHorizontalGroup(
            ForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForumLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(ForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForumLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ForumLayout.setVerticalGroup(
            ForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        Accueil.add(Forum, "card7");

        getContentPane().add(Accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 194, 930, 430));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\USTO-MB_logo--TRANSPAR22.png")); // NOI18N
        jLabel1.setText("Université des sciences et technologies Oran Mohamed Boudiaf");
        jPanel3.add(jLabel1);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_student_male_120px.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 125, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        Accueil.removeAll();
/*jPanel5.removeAll();
jPanel5.repaint();
jPanel5.revalidate();
jPanel5.add(Coursbtns);*/
       

        Accueil.repaint();

        Accueil.revalidate();

        Accueil.add(Cours);


        //jPanel5.repaint();
        Accueil.repaint();
        jLabel6.repaint();
        jLabel8.repaint();
        //jPanel5.revalidate();
        Accueil.revalidate();        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7MouseClicked



    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered

        jLabel7.setEnabled(true);    // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7MouseEntered



    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited

        jLabel7.setEnabled(false);  // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7MouseExited



    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered

        jLabel9.setEnabled(true);        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel9MouseEntered



    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited

        jLabel9.setEnabled(false); // TODO add your handling code here:

    }//GEN-LAST:event_jLabel9MouseExited



    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered

        jLabel10.setEnabled(true);        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel10MouseEntered



    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited

        jLabel10.setEnabled(false);  // TODO add your handling code here:

    }//GEN-LAST:event_jLabel10MouseExited



    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered

        jLabel8.setEnabled(true);        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8MouseEntered



    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited

        jLabel8.setEnabled(false);        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8MouseExited



    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

 Accueil.removeAll();
/*jPanel5.removeAll();
jPanel5.repaint();
jPanel5.revalidate();
jPanel5.add(Exebtns);*/


        Accueil.repaint();
        Accueil.revalidate();
        Accueil.add(Exercices);

        //jPanel5.repaint();
        jLabel6.repaint();
        jLabel8.repaint();
        Accueil.repaint();
        //jPanel5.revalidate();
        Accueil.revalidate();         // TODO add your handling code here:

    }//GEN-LAST:event_jLabel9MouseClicked



    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

 Accueil.removeAll();
/*jPanel5.removeAll();
jPanel5.repaint();
jPanel5.revalidate();
jPanel5.add(Affbtns);*/

        Accueil.repaint();

        Accueil.revalidate();

        

        Accueil.add(Affichage);


        //jPanel5.repaint();
        Accueil.repaint();
        jLabel6.repaint();
        jLabel8.repaint();
        //jPanel5.revalidate();
        Accueil.revalidate();         // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8MouseClicked



    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
//jPanel5.removeAll();
Accueil.removeAll();
//jPanel5.repaint();
Accueil.repaint();
//jPanel5.revalidate();
 Accueil.revalidate();
//jPanel5.add(Tpbtns);
        Accueil.add(TP);

        
        //jPanel5.repaint();
        Accueil.repaint();
        jLabel6.repaint();
        jLabel8.repaint();
        //jPanel5.revalidate();
        Accueil.revalidate();         // TODO add your handling code here:

    }//GEN-LAST:event_jLabel10MouseClicked



    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

/*jPanel5.removeAll();
jPanel5.repaint();
jPanel5.revalidate();
jPanel5.add(Accbtns);*/
Accueil.removeAll();
Accueil.add(Principale);
//jPanel5.repaint();
Accueil.repaint();
jLabel6.repaint();
jLabel8.repaint();
//jPanel5.revalidate();
Accueil.revalidate();
       
    }//GEN-LAST:event_jButton5ActionPerformed



    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Accueil.removeAll();
        Accueil.repaint();

        Accueil.revalidate();

        Accueil.add(Forum);
        Accueil.repaint();
        jLabel6.repaint();
        jLabel8.repaint();
        Accueil.revalidate();   // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
Index i = new Index();
i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(EspaceEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(EspaceEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(EspaceEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(EspaceEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new EspaceEns().setVisible(true);

            }

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JPanel Affichage;
    private javax.swing.JPanel Cours;
    private javax.swing.JPanel CoursPane;
    private javax.swing.JPanel Exercices;
    private javax.swing.JPanel ExercicesPane;
    private javax.swing.JPanel Forum;
    private javax.swing.JPanel Principale;
    private javax.swing.JPanel TP;
    private javax.swing.JPanel TPpane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}

