
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ISMAIL
 */
public class FormEtud extends javax.swing.JFrame {

    /**
     * Creates new form FormEtudiant
     */
    public FormEtud() {
        initComponents();
        jLabel10.setIcon(ResizeImage("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_photo_gallery_125px.png",jLabel10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(345, 0));
        setPreferredSize(new java.awt.Dimension(813, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 720));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 765));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Formulaire d'Inscription Etudiant :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 78, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licence 1", "Licence 2", "Licence 3", "Master 1", "Master 2" }));
        jComboBox1.setSelectedIndex(-1);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 630, 211, 30));

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.setNothingAllowed(false);
    dateChooserCombo1.setFormat(2);
    dateChooserCombo1.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
    jPanel1.add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 327, 210, 34));

    buttonGroup2.add(jRadioButton5);
    jRadioButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
    jRadioButton5.setText("Autre");
    jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 396, 75, -1));

    buttonGroup2.add(jRadioButton4);
    jRadioButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
    jRadioButton4.setText("Femme");
    jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 396, 63, -1));

    buttonGroup2.add(jRadioButton3);
    jRadioButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
    jRadioButton3.setText("Homme ");
    jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 396, -1, -1));

    jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel16.setText("Nom :");
    jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 158, 187, 34));
    jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 162, 211, 30));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel6.setText("Email :");
    jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 453, 187, 34));

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel7.setText("Nouveau mot de passe :");
    jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 513, 187, 34));

    jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel8.setText("Confirmer le mot de passe :");
    jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 565, 187, 34));

    jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel9.setText("Année d'étude :");
    jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 630, 187, 34));

    jTextField4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField4ActionPerformed(evt);
        }
    });
    jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 457, 212, 30));

    jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_photo_gallery_125px.png")); // NOI18N
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 130, 120));

    jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton2.setText("Ajouter ");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 220, 80, 30));

    jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel11.setText("Sexe :");
    jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 388, 187, 34));

    jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel12.setText("Date de Naissance :");
    jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 327, 187, 34));
    jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 270, 211, 30));

    jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel14.setText("Nom d'utilisateur :");
    jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 266, 187, 34));

    jTextField8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField8ActionPerformed(evt);
        }
    });
    jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 218, 211, 30));

    jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel15.setText("Prénom :");
    jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 214, 187, 34));

    jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton4.setText("Confirmer");
    jButton4.setPreferredSize(new java.awt.Dimension(75, 25));
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 660, 120, 40));

    jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)));

    jLabel5.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 102, 153));
    jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_online_support_25px.png")); // NOI18N
    jLabel5.setText("Contact.");
    jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel2.add(jLabel5);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel3.setText(" ");
    jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
    jPanel2.add(jLabel3);

    jLabel13.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(0, 102, 153));
    jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_info_50px_2.png")); // NOI18N
    jLabel13.setText("Aide.");
    jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel2.add(jLabel13);

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 800, 80));

    jPanel3.setPreferredSize(new java.awt.Dimension(800, 60));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Serif", 1, 11)); // NOI18N
    jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\USTO-MB_logo--TRANSPAR22.png")); // NOI18N
    jLabel1.setText("Université des sciences et technologies Oran Mohamed Boudiaf");
    jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 390, 40));

    jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ISMAIL\\Documents\\NetBeansProjects\\BlogIHM\\src\\main\\java\\com\\mycompany\\blogihm\\icons8_return_32px.png")); // NOI18N
    jButton1.setBorder(null);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));

    jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 210, 30));

    jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 210, 30));

    jScrollPane2.setViewportView(jPanel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabel10.setIcon(ResizeImage(path,jLabel10));
        }

        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Index index = new Index();
        index.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEtud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEtud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEtud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEtud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEtud().setVisible(true);
            }
        });
    }
    
    public ImageIcon ResizeImage(String ImagePath,JLabel label)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
